FROM lambci/lambda:build-nodejs12.x

ADD package* ./
ADD src ./

RUN pwd

RUN npm install

RUN find /var/task -type d -print0 | xargs -0 chmod ugo+rx && \
    find /var/task -type f -print0 | xargs -0 chmod ugo+r

ARG ZIPFILE=lambda.zip
RUN zip --quiet -9r /${ZIPFILE}  .

FROM scratch
ARG ZIPFILE
COPY --from=0 /${ZIPFILE} /
